---
title: "Untitled"
author: "Ijeamaka Anyene"
date: "3/31/2020"
output: html_document
---

```{r}
library(sp)
library(sf)
library(raster)
library(rgdal)
library(dplyr)
library(tidyr)
```

```{r}
sf_neighborhoods = st_read(here::here("shapefiles", "Analysis Neighborhoods - 2010 census tracts assigned to neighborhoods.geojson"))

sf_zipcodes = st_read(here::here("shapefiles", "Bay Area ZIP Codes.geojson"))
```

```{r}
pm_locations = readr::read_csv(here::here("data", "Parking_Meter",
                                          "Parking_Meters.csv"))
```

```{r}
sf_pm_locations = st_as_sf(pm_locations, coords = c("LONGITUDE", "LATITUDE"),
                           crs = st_crs(sf_neighborhoods))
```

```{r}
# Checking that they overlay
plot(st_geometry(sf_neighborhoods))
plot(sf_pm_locations, add = TRUE)
```

```{r}
st_crs(sf_neighborhoods)
st_crs(sf_zipcodes)
st_crs(sf_pm_locations)
```


```{r}
neighborhoods_zips_pm = st_join(sf_pm_locations, sf_neighborhoods) %>%
  st_join(., sf_zipcodes)
```

```{r}
final_neighborhoods_zips_pm = neighborhoods_zips_pm %>%
  dplyr::select(OBJECTID, PARKING_SPACE_ID, POST_ID, nhood, zip)
```

```{r}
plot(final_neighborhoods_zips_pm)
```

```{r}
rm(neighborhoods_zips_pm, pm_locations, 
   sf_neighborhoods, sf_pm_locations,
   sf_zipcodes)
```

```{r}
readr::write_csv(final_neighborhoods_zips_pm, here::here("data", 
                                                         "exported_data",
                                                         "parking_meters_neighborhoods_zipcodes.csv"))
```

```{r}
#final_neighborhoods_zips_pm = readr::read_csv(here::here("data", "exported_data", #"parking_meters_neighborhoods_zipcodes.csv"))
```

```{r}
group_nhood = function(df){
  final_df = left_join(df, final_neighborhoods_zips_pm,
                       by = c("POST_ID"="POST_ID")) %>% # Adds in neighborhood information
    mutate(start_date_new = lubridate::date(SESSION_START_DT),
         end_date_new = lubridate::date(SESSION_END_DT)) %>% # Remove HMS from dates
    group_by(start_date_new, nhood) %>%
    summarise(num_parking_meters = n()) %>% # Utilization of parking meters by neighborhood
    ungroup()
    
}
```

```{r}
pm_jan_feb = readr::read_csv(here::here("data", "Parking_Meter",                           "20190101_20190228_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
test_sample = sample(seq(1:4353703), 3000, replace = FALSE)
```

```{r}
test_data = pm_jan_feb[test_sample, ]
test_group = group_nhood(test_data)
```


```{r}
neighborhood_2019_jan_feb_grouped = group_nhood(pm_jan_feb)
```

```{r}
pm_mar_apr = readr::read_csv(here::here("data", "Parking_Meter",                           "20190301_20190430_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
neighborhood_2019_mar_apr_grouped = group_nhood(pm_mar_apr)
```

```{r}
rm(pm_jan_feb, pm_mar_apr)
```

```{r}
pm_may_jun = readr::read_csv(here::here("data", "Parking_Meter",                           "20190501_20190630_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
neighborhood_2019_may_jun_grouped = group_nhood(pm_may_jun)
```

```{r}
rm(pm_may_jun)
```

```{r}
pm_jul_aug = readr::read_csv(here::here("data", "Parking_Meter",                           "20190701_20190831_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
neighborhood_2019_jul_aug_grouped = group_nhood(pm_jul_aug)
```

```{r}
rm(pm_jul_aug)
```

```{r}
pm_sep_oct = readr::read_csv(here::here("data", "Parking_Meter",                           "20190901_20191031_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
neighborhood_2019_sep_oct_grouped = group_nhood(pm_sep_oct)
```

```{r}
rm(pm_sep_oct)
```

```{r}
pm_nov_march = readr::read_csv(here::here("data", "Parking_Meter", "20191101_20200330_SFMTA_Parking_Meter_Detailed_Revenue_Transactions.csv"))
```

```{r}
neighborhood_2019_nov_march_grouped = group_nhood(pm_nov_march)
```

```{r}
rm(pm_nov_march)
```

```{r}
nhood_total_parkingmeters_2019_2020 = bind_rows(neighborhood_2019_nov_march_grouped,
                                      neighborhood_2019_sep_oct_grouped,
                                      neighborhood_2019_jul_aug_grouped,
                                      neighborhood_2019_may_jun_grouped,
                                      neighborhood_2019_mar_apr_grouped,
                                      neighborhood_2019_jan_feb_grouped) %>%
  mutate(wday = lubridate::wday(start_date_new)) %>%
  filter(wday != 1)
```

```{r}
readr::write_csv(nhood_total_parkingmeters_2019_2020,
                 here::here("data", "exported_data", "total_nhood_parking_meter_2019_2020.csv"))
```




























